FROM python:3.12-slim-bullseye

RUN apt-get update && apt-get clean && apt-get install -y \
    libpq-dev gcc \
    --fix-missing \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --upgrade pip setuptools && pip install --no-cache-dir -r requirements.txt

COPY . .
EXPOSE 8000
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]