# FROM python:3.12-slim-bookworm

# RUN apt-get update && apt-get install -y \
#     libpq-dev gcc \
#     --fix-missing \
#     && rm -rf /var/lib/api/lists/*

# WORKDIR /app

# COPY requirements.txt .

# RUN pip install --upgrade pip setuptools && pip install --no-cache-dir -r requirements.txt
# COPY . .
# EXPOSE 8000
# CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

# ======================================== Above images has size 685 MB


# Smaller image
# Stage 1: Builder Image
FROM python:3.12-slim-bookworm AS builder

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    build-essential \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --upgrade pip setuptools && pip install --no-cache-dir -r requirements.txt

# Stage 2: Final Lightweight Image
FROM python:3.12-slim-bookworm

WORKDIR /app
COPY --from=builder /usr/local/lib/python3.12 /usr/local/lib/python3.12
COPY . .

EXPOSE 8000
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
