# Generated by Django 5.1.7 on 2025-03-29 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "incident_id",
                    models.CharField(
                        editable=False,
                        max_length=15,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("reporter_name", models.CharField(max_length=255)),
                ("reporter_email", models.EmailField(max_length=254)),
                (
                    "reporter_phone",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("details", models.TextField(verbose_name="Incident Detail")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("enterprise", "Enterprise"),
                            ("government", "Government"),
                        ],
                        default="enterprise",
                        max_length=12,
                        verbose_name="User type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        default="low", max_length=8, verbose_name="Priority"
                    ),
                ),
                (
                    "reported_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Reported date"
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
