# Generated by Django 5.1.7 on 2025-03-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_incident"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="low",
                max_length=8,
                verbose_name="Priority",
            ),
        ),
    ]
